name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Flutter SDK
        id: cache-flutter
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-3.29.0-${{ runner.os }}

      - name: Install Flutter (Only if Not Cached)
        if: steps.cache-flutter.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0

      - name: Verify Flutter & Dart Installation
        run: |
          flutter doctor
          flutter --version
          dart --version

      - name: Cache Pub Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-cache-${{ runner.os }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            pub-cache-${{ runner.os }}-

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Unit Tests
        run: flutter test

  build-windows:
    name: Build Windows Release
    runs-on: windows-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows Executable
        run: flutter build windows --release --verbose

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release/

  build-macos:
    name: Build macOS Release
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos --release --verbose

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/

  build-linux:
    name: Build Linux Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Linux Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          ninja-build cmake pkg-config \
          libgtk-3-dev libblkid-dev \
          libsecret-1-dev libjsoncpp-dev \
          clang lld liblzma-dev \
          libayatana-appindicator3-dev

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Linux Executable (Debug Mode)
        run: flutter build linux --release --verbose

      - name: Upload Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/bundle/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows-release
          path: windows-release/

      - name: Download macOS Build
        uses: actions/download-artifact@v4
        with:
          name: macos-release
          path: macos-release/

      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: linux-release
          path: linux-release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: OllamaUI ${{ github.ref_name }}
          body: |
            ## Changes in this release
            - Automated build via GitHub Actions
            - Supports Windows, macOS, and Linux
          draft: false
          prerelease: false
          files: |
            windows-release/*
            macos-release/*
            linux-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # ✅ Use Personal Access Token (PAT)
